[package]
name = "causeway-lambda-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-common = { path = "../../../common" }
tokio = { version = "1.28", features = ["full"] }
aws-config = "0.56.0"
aws-sdk-lambda = "0.30.0"
aws-smithy-types = "0.56.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
