[package]
name = "causal-lambda-extension"
version = "0.1.0"
edition = "2021"
description = "AWS Lambda extension for the Causal distributed systems debugger"

[dependencies]
lambda_extension = "0.10.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
async-trait = "0.1"
once_cell = "1.18"
mimalloc = { version = "0.1", optional = true }
flate2 = "1.0"
uuid = { version = "1.4", features = ["v4"] }
crc32fast = "1.3"
futures = "0.3"

# Internal dependencies
agent-core = { path = "../../../core/lib", features = ["lambda"] }
causal-collectors = { path = "../../../collectors", features = ["aws"] }
causal-telemetry = { path = "../../../telemetry" }

[features]
default = ["mimalloc"]
mimalloc = ["dep:mimalloc", "agent-core/mimalloc"]
minimal_deps = ["agent-core/minimal_deps"]

[profile.release]
lto = "fat"         # Link-time optimization
codegen-units = 1   # Maximize optimizations
panic = "abort"     # Smaller binary size
strip = true        # Strip symbols
opt-level = 3       # Maximum optimization

[[bin]]
name = "causal-lambda-extension"
path = "src/main.rs"
