[package]
name = "causeway-lambda-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-core = { path = "../../../core/lib" }
agent-common = { path = "../../../common" }
tokio = { version = "1.28", features = ["full"] }
lambda_extension = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
anyhow = "1.0"
aws-config = "0.56.0"
aws-sdk-s3 = "0.30.0"
reqwest = { version = "0.11", features = ["json"] }

