[package]
name = "causeway-lambda-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_extension = "0.10.0"
tokio = { version = "1.28", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
async-trait = "0.1"
heapless = "0.7"
once_cell = "1.18"
mimalloc = "0.1"
nix = "0.27"
flate2 = "1.0"
uuid = { version = "1.4", features = ["v4"] }
fnv = "1.0"
crc32fast = "1.3"
fastrand = "2.0"
futures = "0.3"
memmap2 = "0.7"
agent-core = { path = "../../../core/lib", features = ["lambda", "minimal_deps", "lambda_extension"] }

[profile.release]
lto = "fat"         # Link-time optimization
codegen-units = 1   # Maximize optimizations
panic = "abort"     # Smaller binary size
strip = true        # Strip symbols
opt-level = 3       # Maximum optimization
