name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cd backend && cargo fmt --all -- --check
      - name: Clippy
        run: cd backend && cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cd backend && cargo test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: 
        version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: cd frontend && pnpm install --frozen-lockfile
      - name: Lint
        run: cd frontend && pnpm run lint
      - name: Check
        run: cd frontend && pnpm run check
      - name: Build
        run: cd frontend && pnpm run build
